# npm install -g eslint babel-eslint eslint-plugin-react eslint-plugin-import
env:
  browser: true
  node: true
  es6: true
extends:
  - eslint:recommended
plugins:
  - import
  - react
parserOptions:
  ecmaVersion: 6,
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  indent: [error, 2]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi: [error, never]

