env:
  browser: true
  node: true
  es6: true
extends:
  - eslint:recommended
plugins:
  - import
  - react
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
rules:
  indent: [error, 2]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi: [error, always]

